// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
   GetEnvironmentData,
   GetEnvironmentResponses,
   GetPartnerByPartnerNummerData,
   GetPartnerByPartnerNummerResponses,
   LadeDruckauftraegeData,
   LadeDruckauftraegeResponses,
   LadeDruckwegeData,
   LadeDruckwegeResponses,
   LadeErweiterterHaushaltData,
   LadeErweiterterHaushaltResponses,
   SpeichernAllDruckwegeToOfflineData,
   SpeichernAllDruckwegeToOfflineResponses,
   SpeichernAllDruckwegeToOnlineData,
   SpeichernAllDruckwegeToOnlineResponses,
   SpeichernOfflineDruckwegData,
   SpeichernOfflineDruckwegResponses,
   SpeichernOnlineDruckwegData,
   SpeichernOnlineDruckwegResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
   TData,
   ThrowOnError
> & {
   /**
    * You can provide a client instance returned by `createClient()` instead of
    * individual options. This might be also useful if you want to implement a
    * custom client.
    */
   client?: Client;
   /**
    * You can pass arbitrary values through the `meta` object. This can be
    * used to access values that aren't defined as part of the SDK function.
    */
   meta?: Record<string, unknown>;
};

export const speichernOnlineDruckweg = <ThrowOnError extends boolean = false>(
   options: Options<SpeichernOnlineDruckwegData, ThrowOnError>
) => {
   return (options.client ?? client).post<SpeichernOnlineDruckwegResponses, unknown, ThrowOnError>({
      url: '/rest/partner/speichernOnlineDruckweg',
      ...options,
      headers: {
         'Content-Type': 'application/json',
         ...options.headers,
      },
   });
};

export const speichernOfflineDruckweg = <ThrowOnError extends boolean = false>(
   options: Options<SpeichernOfflineDruckwegData, ThrowOnError>
) => {
   return (options.client ?? client).post<SpeichernOfflineDruckwegResponses, unknown, ThrowOnError>({
      url: '/rest/partner/speichernOfflineDruckweg',
      ...options,
      headers: {
         'Content-Type': 'application/json',
         ...options.headers,
      },
   });
};

export const speichernAllDruckwegeToOnline = <ThrowOnError extends boolean = false>(
   options: Options<SpeichernAllDruckwegeToOnlineData, ThrowOnError>
) => {
   return (options.client ?? client).post<SpeichernAllDruckwegeToOnlineResponses, unknown, ThrowOnError>({
      url: '/rest/partner/speichernAllDruckwegeToOnline',
      ...options,
      headers: {
         'Content-Type': 'application/json',
         ...options.headers,
      },
   });
};

export const speichernAllDruckwegeToOffline = <ThrowOnError extends boolean = false>(
   options: Options<SpeichernAllDruckwegeToOfflineData, ThrowOnError>
) => {
   return (options.client ?? client).post<SpeichernAllDruckwegeToOfflineResponses, unknown, ThrowOnError>({
      url: '/rest/partner/speichernAllDruckwegeToOffline',
      ...options,
      headers: {
         'Content-Type': 'application/json',
         ...options.headers,
      },
   });
};

export const getPartnerByPartnerNummer = <ThrowOnError extends boolean = false>(
   options: Options<GetPartnerByPartnerNummerData, ThrowOnError>
) => {
   return (options.client ?? client).get<GetPartnerByPartnerNummerResponses, unknown, ThrowOnError>({
      url: '/rest/partner/ladePartnerByParNummer',
      ...options,
   });
};

export const ladeErweiterterHaushalt = <ThrowOnError extends boolean = false>(
   options: Options<LadeErweiterterHaushaltData, ThrowOnError>
) => {
   return (options.client ?? client).get<LadeErweiterterHaushaltResponses, unknown, ThrowOnError>({
      url: '/rest/partner/ladeErweiterterHaushalt',
      ...options,
   });
};

export const ladeDruckwege = <ThrowOnError extends boolean = false>(
   options: Options<LadeDruckwegeData, ThrowOnError>
) => {
   return (options.client ?? client).get<LadeDruckwegeResponses, unknown, ThrowOnError>({
      url: '/rest/partner/ladeDruckwegeByParNummer',
      ...options,
   });
};

export const ladeDruckauftraege = <ThrowOnError extends boolean = false>(
   options: Options<LadeDruckauftraegeData, ThrowOnError>
) => {
   return (options.client ?? client).get<LadeDruckauftraegeResponses, unknown, ThrowOnError>({
      url: '/rest/partner/ladeDruckauftraege',
      ...options,
   });
};

export const getEnvironment = <ThrowOnError extends boolean = false>(
   options?: Options<GetEnvironmentData, ThrowOnError>
) => {
   return (options?.client ?? client).get<GetEnvironmentResponses, unknown, ThrowOnError>({
      url: '/rest/env',
      ...options,
   });
};
