// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
   baseUrl: 'http://localhost:8080/cosmos-kunde-kundenprofil-app' | (string & {});
};

export type Druckweg = {
   vsnr: number;
   sparte: string;
   druckweg: string;
};

export type BeschwerdeListeEintrag = {
   validator?: unknown;
   bswNummer?: string;
   bswBswNummerVorgaenger?: string;
   bswEingebFaAnmerkung?: string;
   bswEingebFaEntscheidung?: string;
   bswTelefonnotiz?: string;
};

export type BesondereRollen = {
   validator?: unknown;
   vertrag?: string;
   sparte?: string;
   parNummerVn?: string;
   rolle?: string;
};

export type Kommunikationsweg = {
   kommunikationsWegId: number;
   updateZahl: string;
   kommunikationsWegArt: 'EMAIL' | 'FAX' | 'TELEFON' | 'MOBILFUNK' | 'UNBEKANNT';
   kommunikationsWegStatus: 'DIENSTLICH' | 'PRIVAT' | 'UNBEKANNT';
   anschluss: string;
   wochenTagVon?: 'MONTAG' | 'DIENSTAG' | 'MITTWOCH' | 'DONNERSTAG' | 'FREITAG' | 'SAMSTAG' | 'SONNTAG' | 'UNBEKANNT';
   wochenTagBis?: 'MONTAG' | 'DIENSTAG' | 'MITTWOCH' | 'DONNERSTAG' | 'FREITAG' | 'SAMSTAG' | 'SONNTAG' | 'UNBEKANNT';
   uhrZeitVon?: string;
   uhrZeitBis?: string;
   erstellungsZeitpunkt: string;
   aenderungsZeitpunkt?: string;
   gueltigkeitsBeginn: string;
   uwgKanal?: string;
   verifikationKanal?: string;
   uwgAnschluss?: string;
   uwgStatuscode?: string;
   verifikationStatuscode?: string;
   herkunft?: string;
   anzahlNachfass?: string;
   wewUwgStatuscode?: string;
   pmklUwgStatuscode?: string;
   wewErstellungsZeitpunkt?: string;
   wewGueltigkeitsBeginn?: string;
   wewGueltigkeitsEnde?: string;
};

export type KundenRentaSparteListe = {
   sparte?: string;
   jahr?: string;
   beitraege?: string;
   anzahlSchaden?: string;
   schadenaufwand?: string;
   quote?: string;
};

export type Kundenprofil = {
   parNummer?: number;
   korrelationsid?: string;
   vertriebsweg?: Vertriebsweg;
   kundeSeit?: string;
   zahlungsinfo?: ZahlungsInfo;
   kundenprofilRentabilitaetGesamt?: KundenprofilRentabilitaetGesamt;
   kundenprofilRentabilitaet?: Array<KundenprofilRentabilitaet>;
   beschwerdeListeEintrag?: Array<BeschwerdeListeEintrag>;
   mahnvertragsDaten?: Array<MahnvertragsDatenEintrag>;
   rentaLeistungListe?: Array<RentaLeistungListe>;
   vertragsinfoSparteListeEintrag?: Array<VertragsinfoSparteListeEintrag>;
   vertragsinfoListeEintrag?: Array<VertragsinfoListeEintrag>;
   kundenRentaSparteListes?: Array<KundenRentaSparteListe>;
   rentaSchadenListes?: Array<RentaSchadenListe>;
   besondereRollen?: Array<BesondereRollen>;
   mahnhistorie?: Array<Mahnhistorie>;
   uniwagnis?: Array<Uniwagnis>;
   uniwagnisSparte?: Array<UniwagnisSparte>;
};

export type KundenprofilRentabilitaet = {
   validator?: unknown;
   jahr?: string;
   beitraege?: string;
   anzahlSchaden?: string;
   schadenaufwand?: string;
   quote?: string;
};

export type KundenprofilRentabilitaetGesamt = {
   validator?: unknown;
   gesamtJahresBeitrag?: string;
   kompositSchadenquote?: string;
   anzahlLeistung?: string;
   summeLeistung?: string;
   anzahlSchaden?: string;
   summeSchaden?: string;
};

export type Mahnhistorie = {
   vertrag?: string;
   beginndatum?: string;
   endedatum?: string;
   grund?: string;
   creditreform?: string;
};

export type MahnvertragsDatenEintrag = {
   validator?: unknown;
   vertrag?: string;
   saldo?: string;
   mahnverfahren?: string;
   unbezahltSeit?: string;
   mahnzweig?: string;
   grund?: string;
};

export type Partner = {
   validator?: unknown;
   partnerNummer: number;
   anrede?:
      | 'SONSTIGE'
      | 'MADEMOISELLE'
      | 'HERR'
      | 'FRAU'
      | 'EHELEUTE'
      | 'ERBENGEMEINSCHAFT'
      | 'FIRMA'
      | 'HAUSVERWALTUNG'
      | 'EIGENTUEMERGEMEINSCHAFT'
      | 'UNBEKANNT';
   anredeCode?: number;
   name: string;
   vorname?: string;
   geburtsDatum?: string;
   geburtsJahr?: string;
   adressen?: Array<PartnerAdresse>;
   sterbedatum?: string;
   status?: 'KUNDENABLEHNUNG_KFZ' | 'STATUS_GRUEN' | 'STATUS_TOT' | 'UNBEKANNT';
   titel?: 'DR' | 'PROF' | 'PROF_DR' | 'DR_MED' | 'KEIN_TITEL';
   berufBezeichnung?: string;
   berufCode?: string;
   letzteAenderung?: string;
   scoring?: 'GRAY' | 'GREEN' | 'ORANGE' | 'RED';
   beschaeftigungsverh?: string;
   beschaeftigungCode?: string;
   familienStand?:
      | 'GETRENNTLEBEND_GESCHIEDEN'
      | 'UNVERHEIRATET_SINGLE'
      | 'VERHEIRATET_EHEPAAR'
      | 'ZUSAMMENLEBEND_PAAR'
      | 'UNBEKANNT';
   familienStandCode?: string;
   anzahlKinder?: number;
   geburtslandCode?: string;
   geburtsOrt?: string;
   staatsangehoerigkeitCode?: string;
   haushaltsRolle?: 'CHEF' | 'MITGLIED';
   updateZahl?: number;
};

export type PartnerAdresse = {
   validator?: unknown;
   adressId?: string;
   laufendeNummer?: string;
   strasse?: string;
   zusatz?: string;
   hausnummer?: string;
   plz?: string;
   ort?: string;
   land?: string;
   adressTyp?: 'HAUPTWOHNSITZ' | 'ZWEITWOHNSITZ' | 'TEMPORAERER_WOHNSITZ' | 'UNBEKANNT';
   adresstypCode?: string;
   gueltigAb?: string;
   gueltigBis?: string;
   inaktivAb?: string;
   updateZahl?: number;
};

export type PartnerProfil = {
   partner?: Partner;
   kundenprofil?: Kundenprofil;
   haushaltsPartner?: Array<Partner>;
   spartenMappings?: Array<SpartenMapping>;
   kommunikationswege?: Array<Kommunikationsweg>;
};

export type RentaLeistungListe = {
   vertrag?: string;
   sparte?: string;
   leistungsfall?: string;
   leistungsversion?: string;
   ereignisdatum?: string;
   zahlungen?: string;
   leistungsart?: string;
   status?: string;
};

export type RentaSchadenListe = {
   vertrag?: string;
   sparte?: string;
   schadennummer?: string;
   tarifbuendel?: string;
   ereignisdatum?: string;
   meldedatum?: string;
   schadenaufwand?: string;
   reserve?: string;
   rueckkauf?: string;
   schadenart?: string;
};

export type SpartenMapping = {
   key: string;
   value: string;
};

export type Uniwagnis = {
   validator?: unknown;
   uwaw?: string;
   schadensparte?: string;
   schadenursache?: string;
   gesellschaft?: string;
};

export type UniwagnisSparte = {
   sparte?: string;
   anzahlUniwagnis?: string;
};

export type VertragsinfoListeEintrag = {
   validator?: unknown;
   vertag?: string;
   beitrag?: string;
   tarif?: string;
   sparte?: string;
   versicherungssumme?: string;
   vertragsbeginn?: string;
   systemKnz?: string;
   anzahlVertraege?: string;
};

export type VertragsinfoSparteListeEintrag = {
   validator?: unknown;
   sparte?: string;
   anzahlVertraege?: string;
   beitrag?: string;
   versicherungssumme?: string;
};

export type Vertriebsweg = {
   verNummer?: number;
   vertriebswegNummer?: string;
   vertriebswegName?: string;
   vertriebswegDatum?: string;
   vertriebswegSparte?: string;
};

export type ZahlungsInfo = {
   validator?: unknown;
   aktuellerKundensaldo?: string;
   scoringWert?: string;
   scoringDatum?: string;
   anzahlMahnverfahrenOffen?: string;
   anzahlMahnverfahrenHistorie?: string;
   infoText?: string;
};

export type PartnerErweiterterHaushalt = {
   haushaltsPartner?: Array<Partner>;
};

export type Druckauftrag = {
   vsnr: number;
   reportName: string;
   reportBezeichnung: string;
   druckweg: string;
   erstelltAm: string;
   status: string;
   druckauftragTyp: string;
};

export type UserEnvironment = {
   authenticatedUsername?: string;
   tester?: boolean;
   db?: string;
   restTimeout?: number;
};

export type SpeichernOnlineDruckwegData = {
   body: string;
   path?: never;
   query?: never;
   url: '/rest/partner/speichernOnlineDruckweg';
};

export type SpeichernOnlineDruckwegResponses = {
   /**
    * OK
    */
   200: unknown;
};

export type SpeichernOfflineDruckwegData = {
   body: string;
   path?: never;
   query?: never;
   url: '/rest/partner/speichernOfflineDruckweg';
};

export type SpeichernOfflineDruckwegResponses = {
   /**
    * OK
    */
   200: unknown;
};

export type SpeichernAllDruckwegeToOnlineData = {
   body: Array<Druckweg>;
   path?: never;
   query?: never;
   url: '/rest/partner/speichernAllDruckwegeToOnline';
};

export type SpeichernAllDruckwegeToOnlineResponses = {
   /**
    * OK
    */
   200: unknown;
};

export type SpeichernAllDruckwegeToOfflineData = {
   body: Array<Druckweg>;
   path?: never;
   query?: never;
   url: '/rest/partner/speichernAllDruckwegeToOffline';
};

export type SpeichernAllDruckwegeToOfflineResponses = {
   /**
    * OK
    */
   200: unknown;
};

export type GetPartnerByPartnerNummerData = {
   body?: never;
   path?: never;
   query: {
      parNummer: string;
   };
   url: '/rest/partner/ladePartnerByParNummer';
};

export type GetPartnerByPartnerNummerResponses = {
   /**
    * OK
    */
   200: PartnerProfil;
};

export type GetPartnerByPartnerNummerResponse =
   GetPartnerByPartnerNummerResponses[keyof GetPartnerByPartnerNummerResponses];

export type LadeErweiterterHaushaltData = {
   body?: never;
   path?: never;
   query: {
      parNummer: string;
   };
   url: '/rest/partner/ladeErweiterterHaushalt';
};

export type LadeErweiterterHaushaltResponses = {
   /**
    * OK
    */
   200: PartnerErweiterterHaushalt;
};

export type LadeErweiterterHaushaltResponse = LadeErweiterterHaushaltResponses[keyof LadeErweiterterHaushaltResponses];

export type LadeDruckwegeData = {
   body?: never;
   path?: never;
   query: {
      parNummer: string;
   };
   url: '/rest/partner/ladeDruckwegeByParNummer';
};

export type LadeDruckwegeResponses = {
   /**
    * OK
    */
   200: Array<Druckweg>;
};

export type LadeDruckwegeResponse = LadeDruckwegeResponses[keyof LadeDruckwegeResponses];

export type LadeDruckauftraegeData = {
   body?: never;
   path?: never;
   query: {
      vsnr: string;
      ladeAktuelleDruckauftraege: boolean;
      ladeHistorischDruckauftraege: boolean;
   };
   url: '/rest/partner/ladeDruckauftraege';
};

export type LadeDruckauftraegeResponses = {
   /**
    * OK
    */
   200: Array<Druckauftrag>;
};

export type LadeDruckauftraegeResponse = LadeDruckauftraegeResponses[keyof LadeDruckauftraegeResponses];

export type GetEnvironmentData = {
   body?: never;
   path?: never;
   query?: never;
   url: '/rest/env';
};

export type GetEnvironmentResponses = {
   /**
    * OK
    */
   200: UserEnvironment;
};

export type GetEnvironmentResponse = GetEnvironmentResponses[keyof GetEnvironmentResponses];
